# Generated by Django 3.2.8 on 2023-04-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Doctor', 'Doctor'), ('Hospital', 'Hospital')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Ward', 'Ward'), ('ICU', 'ICU'), ('Emergency', 'Emergency')], max_length=100)),
                ('qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('AYUSH', 'AYUSH'), ('BDS', 'BDS'), ('Nursing', 'Nursing')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning (6 AM - 2 AM)'), ('Afternoon', 'Afternoon (2 PM - 8 PM)'), ('Night', 'Night (9 PM - 6 AM)')], max_length=100)),
                ('department', models.CharField(choices=[('Ward', 'Ward'), ('ICU', 'ICU'), ('Emergency', 'Emergency')], max_length=100)),
                ('qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('AYUSH', 'AYUSH'), ('BDS', 'BDS'), ('Nursing', 'Nursing')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
    ]
