# Generated by Django 3.2.8 on 2023-04-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='added_date',
        ),
    ]
