# Generated by Django 3.2.8 on 2023-04-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userregistration_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_id',
            new_name='user',
        ),
    ]
